services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio3_app
    image: portfolio3_app
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - portfolio_network
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    container_name: portfolio3_strapi
    image: portfolio3_strapi
    environment:
      DATABASE_CLIENT: sqlite
    volumes:
      - strapi_data:/app/.tmp
    ports:
      - 1337:1337
    restart: unless-stopped
    networks:
      - portfolio_network

volumes:
  strapi_data:

networks:
  portfolio_network:
    driver: bridge
