services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: portfolio_app_dev
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - portfolio_network_dev
    volumes:
      - .:/app
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile.dev
    container_name: portfolio_strapi_dev
    environment:
      DATABASE_CLIENT: sqlite
    volumes:
      - ./strapi:/app
    ports:
      - 1337:1337
    restart: unless-stopped
    networks:
      - portfolio_network_dev

networks:
  portfolio_network_dev:
    driver: bridge
