services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - portfolio_network
  strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    container_name: portfolio_strapi
    environment:
      DATABASE_CLIENT: sqlite
    volumes:
      - strapi_data:/app/.tmp
    ports:
      - ${STRAPI_PORT}:${STRAPI_PORT}
    restart: unless-stopped
    networks:
      - portfolio_network

volumes:
  strapi_data:

networks:
  portfolio_network:
    driver: bridge
